"""baseline schema

Revision ID: a9db49bf7f24
Revises: 
Create Date: 2026-06-05 15:02:04.513447

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9db49bf7f24'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('unit_system', sa.String(length=16), nullable=False),
    sa.Column('status', sa.Enum('ONBOARDING', 'ACTIVE', 'PAUSED', name='user_status'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('body_metrics',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('body_fat_pct', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('lean_mass_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bmi', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.Enum('SMART_SCALE_SCREENSHOT', 'MANUAL', name='body_metric_source'), nullable=False),
    sa.Column('raw_extracted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_metrics_measured_at'), 'body_metrics', ['measured_at'], unique=False)
    op.create_index(op.f('ix_body_metrics_user_id'), 'body_metrics', ['user_id'], unique=False)
    op.create_table('events',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_event_type'), 'events', ['event_type'], unique=False)
    op.create_index(op.f('ix_events_user_id'), 'events', ['user_id'], unique=False)
    op.create_table('goals',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('CUT', 'BULK', 'MAINTAIN', 'RECOMP', name='goal_type'), nullable=False),
    sa.Column('target_weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goals_user_id'), 'goals', ['user_id'], unique=False)
    op.create_table('nutrition_logs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('logged_for_date', sa.Date(), nullable=False),
    sa.Column('item_name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.Enum('OPEN_FOOD_FACTS', 'LABEL_PHOTO', 'LLM_ESTIMATE', 'MANUAL', name='nutrition_source'), nullable=False),
    sa.Column('quantity', sa.String(length=64), nullable=True),
    sa.Column('calories', sa.Numeric(precision=7, scale=1), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('carbs_g', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('off_barcode', sa.String(length=64), nullable=True),
    sa.Column('raw_extracted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_logs_logged_for_date'), 'nutrition_logs', ['logged_for_date'], unique=False)
    op.create_index(op.f('ix_nutrition_logs_user_id'), 'nutrition_logs', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('sex', sa.String(length=32), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('experience_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='experience_level'), nullable=True),
    sa.Column('equipment_access', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('scheduled_jobs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_type', sa.Enum('NIGHTLY_GENERATION', 'SKIP_CHECK', 'GOAL_REVIEW', name='job_type'), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('run_local_time', sa.Time(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_status', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'job_type', 'target_date', name='uq_job_user_type_date')
    )
    op.create_index(op.f('ix_scheduled_jobs_user_id'), 'scheduled_jobs', ['user_id'], unique=False)
    op.create_table('workout_schedules',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generation_local_time', sa.Time(), nullable=False),
    sa.Column('skip_check_local_time', sa.Time(), nullable=False),
    sa.Column('skip_check_grace_hours', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_schedules_user_id'), 'workout_schedules', ['user_id'], unique=False)
    op.create_table('planned_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('split_label', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'GENERATED', 'COMPLETED', 'SKIPPED', 'MISSED', name='session_status'), nullable=False),
    sa.Column('source_schedule_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_schedule_id'], ['workout_schedules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'scheduled_date', name='uq_user_session_date')
    )
    op.create_index(op.f('ix_planned_sessions_scheduled_date'), 'planned_sessions', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_planned_sessions_user_id'), 'planned_sessions', ['user_id'], unique=False)
    op.create_table('generated_workouts',
    sa.Column('planned_session_id', sa.Uuid(), nullable=False),
    sa.Column('prescription', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('regenerated_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['planned_session_id'], ['planned_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('planned_session_id')
    )
    op.create_table('workout_completions',
    sa.Column('planned_session_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('APPLE_FITNESS_SCREENSHOT', 'MANUAL', 'OTHER', name='completion_source'), nullable=False),
    sa.Column('workout_type', sa.String(length=128), nullable=True),
    sa.Column('duration_min', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('active_calories', sa.Numeric(precision=7, scale=1), nullable=True),
    sa.Column('avg_hr', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_extracted', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['planned_session_id'], ['planned_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_completions_user_id'), 'workout_completions', ['user_id'], unique=False)
    op.create_table('pulse_checks',
    sa.Column('completion_id', sa.Uuid(), nullable=False),
    sa.Column('rpe', sa.SmallInteger(), nullable=True),
    sa.Column('energy', sa.SmallInteger(), nullable=True),
    sa.Column('soreness', sa.SmallInteger(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['completion_id'], ['workout_completions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('completion_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pulse_checks')
    op.drop_index(op.f('ix_workout_completions_user_id'), table_name='workout_completions')
    op.drop_table('workout_completions')
    op.drop_table('generated_workouts')
    op.drop_index(op.f('ix_planned_sessions_user_id'), table_name='planned_sessions')
    op.drop_index(op.f('ix_planned_sessions_scheduled_date'), table_name='planned_sessions')
    op.drop_table('planned_sessions')
    op.drop_index(op.f('ix_workout_schedules_user_id'), table_name='workout_schedules')
    op.drop_table('workout_schedules')
    op.drop_index(op.f('ix_scheduled_jobs_user_id'), table_name='scheduled_jobs')
    op.drop_table('scheduled_jobs')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_nutrition_logs_user_id'), table_name='nutrition_logs')
    op.drop_index(op.f('ix_nutrition_logs_logged_for_date'), table_name='nutrition_logs')
    op.drop_table('nutrition_logs')
    op.drop_index(op.f('ix_goals_user_id'), table_name='goals')
    op.drop_table('goals')
    op.drop_index(op.f('ix_events_user_id'), table_name='events')
    op.drop_index(op.f('ix_events_event_type'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_body_metrics_user_id'), table_name='body_metrics')
    op.drop_index(op.f('ix_body_metrics_measured_at'), table_name='body_metrics')
    op.drop_table('body_metrics')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
