"""add user next_block_review_on

Revision ID: d1bb4ae254b7
Revises: e2a1c3d4f5a6
Create Date: 2026-06-08 13:07:09.708246

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1bb4ae254b7'
down_revision: str | None = 'e2a1c3d4f5a6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('next_block_review_on', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'next_block_review_on')
    # ### end Alembic commands ###
